### ISSUE TITLE
(add) Option to format readable HTML

### ISSUE THREAD

**Issue by igalic** [Dalgona/Serum#134]
I like to have produce readable HTML on my site.

Is there an option i can pass to Serum / Earmark to do that?

**Comment by Dalgona** [comment]
As far as I know, there's no such option in Earmark. Even Floki, which is a HTML parser used internally by Serum, does not have one.

Still, I would like to have this feature in Serum one day, by implementing HTML pretty formatter on my own (if necessary 😅).

**Comment by Dalgona** [comment]
In the meantime, I'm sad to say this, you might want to temporarily rely on an external program and optionally a shell script for automation.

**Comment by igalic** [comment]
here's my `Makefile` to build my websites:

```make
tidy!=(which tidy5 || which tidy)
update-static:
	rm -rf site/
	env TZ=UTC MIX_ENV=prod mix serum.build
	$(tidy) -config tidy.config site/*.html || true
	$(tidy) -config tidy.config site/thoughts/*.html || true
```

with the following tidy.config:

```yaml
indent: auto
indent-spaces: 4
tidy-mark: no
punctuation-wrap: yes
vertical-space: yes
wrap: 111
quiet: yes
write-back: yes
```

i'm happy with this solution, and will close this issue for now.
